name: beyond_transformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pytorch::pytorch>=1.9.0
  - numpy>=1.21.0
  - matplotlib>=3.3.0
  - psutil>=5.8.0
  - pip:
    - -r requirements/requirements.txt
    - -r requirements/requirements-test.txt
    - -r requirements/requirements-experiments.txt