model:
  input_dim: 784
  state_dim: 128
  num_states: 16
  output_dim: 10
  gate_type: "gru"

training:
  epochs: 5
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"

data:
  dataset: "mnist"
  num_samples: 1000

experiment:
  name: "debug_config"
  description: "Minimal configuration for debugging"